In [1]:
import numpy as np

# Creating ndarrays

In [2]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [3]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr2.ndim,arr1.ndim

(2, 1)

In [8]:
arr2.shape,arr1.shape

((2, 4), (5,))

In [9]:
arr2.dtype,arr1.dtype

(dtype('int32'), dtype('float64'))

creating random arrays

In [12]:
np.zeros((2,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [13]:
np.ones((2,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [21]:
x=np.empty((2,4,3))
x

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [18]:
x.ndim

3

In [24]:
np.ones_like(x)#takes an existing array and produces an array of the same size filled with 1

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

np.zeros_like,np.empty_like does the same thing

using range in numpy

In [23]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

create identity matrix on NxN

In [29]:
np.identity(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [30]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

# Data types for ndarrays

In [32]:
arr1=np.array([1,2,3],dtype=np.float64)
arr1

array([ 1.,  2.,  3.])

In [33]:
#convert the dtype of one array to other

In [36]:
arr2=np.array([1,2,3,4])
new=arr2.astype(np.float64)
new

array([ 1.,  2.,  3.,  4.])

In [37]:
arr=np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [38]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [39]:
numeric_strings=np.array(['12.5','-9.6'],dtype=np.string_)
numeric_strings.astype(float)

array([ 12.5,  -9.6])

# operations between arrays and scalars(vectorization)

In [41]:
arr=np.array([[1,2,3],[4,5,6]])

In [45]:
arr.shape

(2, 3)

In [46]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [48]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [49]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [50]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36]])

operations between differently sized array is called broadcasting

# Basic indexing and slicing

In [53]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr[5]

5

In [55]:
arr[5:8]

array([5, 6, 7])

In [56]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In case of arrays slices are views of the original arrays i.e the data is not copied,and any modofications to the view will be reflected in the original array

In [57]:
arr_slice=arr[5:8]
arr_slice

array([12, 12, 12])

In [58]:
arr_slice[1]=12345
arr_slice

array([   12, 12345,    12])

In [59]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [60]:
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

for copying the numpy array

In [63]:
arr_copy=arr[5:8].copy()
arr_copy

array([64, 64, 64])

In [64]:
arr_copy[1]=24
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [66]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr2d.shape,arr2d.ndim

((3, 3), 2)

In [69]:
arr2d[0]

array([1, 2, 3])

In [71]:
arr2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
arr2d[0][1],arr2d[1][2]

(2, 6)

In [74]:
arr2d[1,2]

6

In [75]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
arr2d[:2,]

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
arr2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [78]:
arr2d[1,:2]

array([4, 5])

# Boolean Indexing

In [85]:
names=np.array(['bob','joe','bob','will','joe','will'])
data=np.empty((6,4))

In [96]:
import random
for i in range(len(data)):
        data[i]=random.random()
data

array([[ 0.54380919,  0.54380919,  0.54380919,  0.54380919],
       [ 0.49004137,  0.49004137,  0.49004137,  0.49004137],
       [ 0.80026787,  0.80026787,  0.80026787,  0.80026787],
       [ 0.12082521,  0.12082521,  0.12082521,  0.12082521],
       [ 0.20652807,  0.20652807,  0.20652807,  0.20652807],
       [ 0.73306211,  0.73306211,  0.73306211,  0.73306211]])

In [97]:
data[names=='bob']

array([[ 0.54380919,  0.54380919,  0.54380919,  0.54380919],
       [ 0.80026787,  0.80026787,  0.80026787,  0.80026787]])

In [102]:
data[(names=='bob') | (names=='joe')]

array([[ 0.54380919,  0.54380919,  0.54380919,  0.54380919],
       [ 0.49004137,  0.49004137,  0.49004137,  0.49004137],
       [ 0.80026787,  0.80026787,  0.80026787,  0.80026787],
       [ 0.20652807,  0.20652807,  0.20652807,  0.20652807]])

In [103]:
data[names != 'bob']

array([[ 0.49004137,  0.49004137,  0.49004137,  0.49004137],
       [ 0.12082521,  0.12082521,  0.12082521,  0.12082521],
       [ 0.20652807,  0.20652807,  0.20652807,  0.20652807],
       [ 0.73306211,  0.73306211,  0.73306211,  0.73306211]])

In [106]:
data[~(names=='bob')]

array([[ 0.49004137,  0.49004137,  0.49004137,  0.49004137],
       [ 0.12082521,  0.12082521,  0.12082521,  0.12082521],
       [ 0.20652807,  0.20652807,  0.20652807,  0.20652807],
       [ 0.73306211,  0.73306211,  0.73306211,  0.73306211]])

In [108]:
data[data<0.4]

array([ 0.12082521,  0.12082521,  0.12082521,  0.12082521,  0.20652807,
        0.20652807,  0.20652807,  0.20652807])

In [109]:
data[data<0.4]=0
data

array([[ 0.54380919,  0.54380919,  0.54380919,  0.54380919],
       [ 0.49004137,  0.49004137,  0.49004137,  0.49004137],
       [ 0.80026787,  0.80026787,  0.80026787,  0.80026787],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.73306211,  0.73306211,  0.73306211,  0.73306211]])

# Fancy Indexing

In [112]:
#Fancy indexing is a ter adopted by numpy to describe indexing using integer arrays.

In [113]:
arr=np.empty((8,4))
arr

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [114]:
for i in range(len(arr)):
    arr[i]=i

In [115]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [116]:
arr[[0,5,7]]

array([[ 0.,  0.,  0.,  0.],
       [ 5.,  5.,  5.,  5.],
       [ 7.,  7.,  7.,  7.]])

In [117]:
arr[-1]

array([ 7.,  7.,  7.,  7.])

In [118]:
arr[[-1,-2,-3]]

array([[ 7.,  7.,  7.,  7.],
       [ 6.,  6.,  6.,  6.],
       [ 5.,  5.,  5.,  5.]])

In [119]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [130]:
arr[[1,2],[0,1]]

array([4, 9])

In [135]:
arr[[1,2]][:,[0,1]]

array([[4, 5],
       [8, 9]])

Fancy indexing unlike slicing copys the data into a new array

In [136]:
arr[1:3,0:2]

array([[4, 5],
       [8, 9]])

# Transposing Arrays and Swapping Axes

In [137]:
arr=np.arange(15).reshape((3,5))

In [138]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [139]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [140]:
np.dot(arr,arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [141]:
arr=np.random.randn(6,3)
arr

array([[ 1.10637832,  1.00844271, -0.06928103],
       [ 2.06588983, -0.29218655,  1.31830119],
       [ 0.39480439, -0.29286651,  0.24606955],
       [ 0.62781085, -0.14155008,  1.47953062],
       [ 1.73715902,  1.23720873, -1.01856512],
       [ 0.98120532,  0.59305647,  0.70100719]])

# Universal Functions:fast elemnt-wise Array Functions

In [1]:
# A universal function or ufunc,is a function that performs elementwise operations on data in ndarrays.(sqrt or exp)

In [7]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [40]:
exp=np.exp(arr)
exp

array([  6.37804566e-01,   9.07949954e+00,   3.42253847e+00,
         1.24171547e+00,   3.70290337e-03,   3.08548702e-02,
         5.99972416e-01])

In [41]:
np.abs(exp)

array([  6.37804566e-01,   9.07949954e+00,   3.42253847e+00,
         1.24171547e+00,   3.70290337e-03,   3.08548702e-02,
         5.99972416e-01])

In [42]:
np.square(arr)

array([  0.20225111,   4.86652016,   1.51384114,   0.04686959,
        31.34474827,  12.09968867,   0.26098979])

In [15]:
#these are refered to as unary ufunc while add or  maximum,take 2 arrays thus binary ufuncs

In [16]:
x=np.random.randn(8)
x

array([-0.27055156, -1.26336124, -2.27438313,  0.38388905,  1.65249387,
       -0.37064535,  0.30734199, -0.68598571])

In [18]:
y=np.random.randn(8)
y

array([-0.46376409,  0.62122068,  0.7308891 ,  0.62188862, -1.13533247,
        0.84860668,  0.02963862,  1.84269397])

In [19]:
np.maximum(x,y)#element wise maximum

array([-0.27055156,  0.62122068,  0.7308891 ,  0.62188862,  1.65249387,
        0.84860668,  0.30734199,  1.84269397])

In [21]:
#while not common a ufuncn can return multiple arrays ,np.modf it returns the fractional and integral part

In [25]:
arr=np.random.randn(7)*5
arr

array([-0.44972337,  2.20601907,  1.23038252,  0.21649387, -5.59863807,
       -3.47846068, -0.5108716 ])

In [31]:
np.modf(arr)

(array([-0.44972337,  0.20601907,  0.23038252,  0.21649387, -0.59863807,
        -0.47846068, -0.5108716 ]), array([-0.,  2.,  1.,  0., -5., -3., -0.]))

In [37]:
x=np.array([1,2,3,4])
y=np.array([2,3,4,2])
np.power(x,y)

array([ 1,  8, 81, 16], dtype=int32)

In [43]:
np.mod(x,y)

array([1, 2, 3, 0], dtype=int32)

In [44]:
np.greater(x,y)

array([False, False, False,  True], dtype=bool)

In [45]:
np.greater_equal(x,y)

array([False, False, False,  True], dtype=bool)

In [47]:
np.logical_or(x,y)

array([ True,  True,  True,  True], dtype=bool)

# Data processing using arrays

In [48]:
#suppose we want to evaluate the function sqrt(x^2+y^2)

In [49]:
#the np.meshgrid takes two 1D  array and produces two 2D matrices corresponding to all pairs(x,y) in the two arrays

In [56]:
points=np.arange(-5,5,0.01) #1000 equally spaced points
points

array([ -5.00000000e+00,  -4.99000000e+00,  -4.98000000e+00,
        -4.97000000e+00,  -4.96000000e+00,  -4.95000000e+00,
        -4.94000000e+00,  -4.93000000e+00,  -4.92000000e+00,
        -4.91000000e+00,  -4.90000000e+00,  -4.89000000e+00,
        -4.88000000e+00,  -4.87000000e+00,  -4.86000000e+00,
        -4.85000000e+00,  -4.84000000e+00,  -4.83000000e+00,
        -4.82000000e+00,  -4.81000000e+00,  -4.80000000e+00,
        -4.79000000e+00,  -4.78000000e+00,  -4.77000000e+00,
        -4.76000000e+00,  -4.75000000e+00,  -4.74000000e+00,
        -4.73000000e+00,  -4.72000000e+00,  -4.71000000e+00,
        -4.70000000e+00,  -4.69000000e+00,  -4.68000000e+00,
        -4.67000000e+00,  -4.66000000e+00,  -4.65000000e+00,
        -4.64000000e+00,  -4.63000000e+00,  -4.62000000e+00,
        -4.61000000e+00,  -4.60000000e+00,  -4.59000000e+00,
        -4.58000000e+00,  -4.57000000e+00,  -4.56000000e+00,
        -4.55000000e+00,  -4.54000000e+00,  -4.53000000e+00,
        -4.52000000e+00,

In [58]:
xs,ys = np.meshgrid(points,points)

In [59]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ..., 
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [60]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [63]:
np.shape(xs)

(1000, 1000)

In [64]:
np.shape(ys)

(1000, 1000)

In [65]:
z = np.sqrt(xs**2 + ys**2)
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [66]:
np.shape(z)

(1000, 1000)

# Expressing conditional logic as Array operations

In [67]:
#the numpy.where is a vectorized version of the ternary expression x if condition else y

In [69]:
xarr=np.array([1.1,1.2,1.3,1.4,1.5])
yarr=np.array([2.1,2.2,2.3,2.4,2.5])
cond=np.array([True,False,True,True,False])
result=[(x if c else y) for x,y,c in zip(xarr,yarr,cond)]
result

[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]

In [74]:
list(zip(xarr,yarr,cond))#zip combines one or more arrays elementwise

[(1.1000000000000001, 2.1000000000000001, True),
 (1.2, 2.2000000000000002, False),
 (1.3, 2.2999999999999998, True),
 (1.3999999999999999, 2.3999999999999999, True),
 (1.5, 2.5, False)]

In [75]:
result=np.where(cond,xarr,yarr)
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [76]:
#The second and third arguments to np.where don,t need to be arrays

In [77]:
arr=np.random.randn(4,4)
arr

array([[ 0.86163013,  1.18186126, -0.67792167,  2.71340396],
       [-0.63677405,  1.88058475, -1.06683503, -0.08404385],
       [ 1.04689441,  1.81144927, -0.08969746,  0.21728978],
       [ 1.56074828, -0.11003536,  1.07455121, -1.42584552]])

In [78]:
np.where(arr>0,2,-2)

array([[ 2,  2, -2,  2],
       [-2,  2, -2, -2],
       [ 2,  2, -2,  2],
       [ 2, -2,  2, -2]])

In [79]:
np.where(arr>0,2,arr)

array([[ 2.        ,  2.        , -0.67792167,  2.        ],
       [-0.63677405,  2.        , -1.06683503, -0.08404385],
       [ 2.        ,  2.        , -0.08969746,  2.        ],
       [ 2.        , -0.11003536,  2.        , -1.42584552]])

In [80]:
#example of where

In [81]:
result=[]
cond1=np.array([True,False,True,True,False])
cond2=np.array([False,True,True,False,True])
n=len(cond1)
for i in range(n):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)
result

[1, 2, 0, 1, 2]

In [82]:
np.where(cond1 & cond2,0,np.where(cond1,1,np.where(cond2,2,3)))

array([1, 2, 0, 1, 2])

# Mathematical and Statistical methods

In [83]:
arr=np.random.randn(5,4)
arr

array([[ 1.57907764,  0.7718473 , -0.62841301,  1.23025309],
       [ 0.28134969,  0.6482842 ,  0.11805659,  0.81790354],
       [ 0.637638  , -1.55872341, -0.96910773, -0.13756662],
       [-1.05846225,  0.39262098, -0.69990888, -0.65777019],
       [-0.49309063,  1.13665057,  2.07602352,  0.52143887]])

In [84]:
np.mean(arr)

0.20040506261284668

In [85]:
np.sum(arr)

4.0081012522569335

In [86]:
arr.mean()

0.20040506261284668

In [87]:
arr.sum()

4.0081012522569335

In [91]:
arr.mean(axis=1)#axis argument is give to find the sum or mean row or coloumn wise(0 -> coloumn,1 -> row)

array([ 0.73819125,  0.4663985 , -0.50693994, -0.50588009,  0.81025558])

In [98]:
arr.sum(0)

array([ 0.94651245,  1.39067964, -0.10334952,  1.77425867])

In [96]:
sum(arr[:,0]),sum(arr[:,1]),sum(arr[:,2]),sum(arr[:,3])#coloumn wise sum

(0.94651245418556829,
 1.3906796436807554,
 -0.10334951900717204,
 1.7742586733977819)

In [99]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# cumulative sum and product axis wise

In [102]:
arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [103]:
arr.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [ ]:
#other statistical methods-> std,var,min,max,argmin,argmax(indices of maximum and minimum elements)

# Methods for Boolean Arrays

In [104]:
#Booleans are coerced to 1(true and 0(false) in the above methods.

In [119]:
arr=np.random.randn(10)
arr

array([-0.09479683,  0.70624944, -0.10386746, -0.31223506, -1.0907904 ,
       -0.14872233,  0.6389965 ,  0.90941341,  0.38780538,  1.96471118])

In [107]:
(arr>0).sum()#No of positive values

4

In [111]:
(arr>0).all(),(arr>0).any()

(False, True)

# Sorting

In [120]:
arr.sort()
arr

array([-1.0907904 , -0.31223506, -0.14872233, -0.10386746, -0.09479683,
        0.38780538,  0.6389965 ,  0.70624944,  0.90941341,  1.96471118])

In [121]:
arr=np.random.randn(5,3)
arr

array([[-1.58258582,  0.6693425 ,  0.19731377],
       [-0.33855614,  0.33271629, -1.60024204],
       [-2.31153076, -0.48042492,  1.66516381],
       [ 0.86414032, -1.12151466,  0.95340501],
       [-1.03125611, -0.29867997,  0.42526859]])

In [122]:
arr.sort(0)#axis wise sorting

In [123]:
arr

array([[-2.31153076, -1.12151466, -1.60024204],
       [-1.58258582, -0.48042492,  0.19731377],
       [-1.03125611, -0.29867997,  0.42526859],
       [-0.33855614,  0.33271629,  0.95340501],
       [ 0.86414032,  0.6693425 ,  1.66516381]])

In [124]:
large_arr=np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05*len(large_arr))] #calculating 5% quantile

-1.730179769906742

In [ ]:
#np.sort creates a copy of the original array without altering the original array

In [125]:
arr=np.random.randn(10)
arr
np.sort(arr)

array([-2.27927032, -0.97768036, -0.67045356, -0.35948305, -0.01173812,
        0.666609  ,  0.90010659,  0.96847956,  1.9747018 ,  2.36322257])

In [126]:
arr

array([-2.27927032, -0.35948305,  2.36322257,  0.90010659,  0.666609  ,
       -0.67045356,  0.96847956, -0.01173812,  1.9747018 , -0.97768036])

# Unique and other Set Logic

In [ ]:
#np.unique returns the sorted unique values in an array

In [2]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], 
      dtype='<U4')

In [3]:
ints=np.array([3,3,3,2,2,1,1,4,4])
np.unique(ints)

array([1, 2, 3, 4])

In [4]:
#Alternative
sorted(set(names))

['Bob', 'Joe', 'Will']

In [5]:
#np.in1d,tests membership of the values in one array in another and returns a boolean array:

In [6]:
values=np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True], dtype=bool)

In [7]:
np.intersect1d(values,[2,3,6])#intersection of two arrays

array([2, 3, 6])

In [8]:
np.union1d(values,[2,3,6])

array([0, 2, 3, 5, 6])

In [9]:
np.setdiff1d(values,[2,3,6])

array([0, 5])

# File input and output with Arrays

# Storing Arrays on Disk in Binary format

In [10]:
#np.save and np.load are used to store and load array data on disk

In [11]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.save('some_array.npy',arr)

In [13]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#for saving multiple arrays in a zip archive using np.savez and extension .npz

In [15]:
arr1=np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [16]:
np.savez('array_archive.npz',a=arr,b=arr1)

In [17]:
arch=np.load('array_archive.npz')

In [18]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arch['b']

array([0, 1, 2, 3, 4])

# Linear Algebra

In [25]:
x=np.array([[1,2,3],[4,5,6]] )
x

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
y=np.array([[6,23],[1,7],[-9,3]])
y

array([[ 6, 23],
       [ 1,  7],
       [-9,  3]])

In [27]:
np.dot(x,y)

array([[-19,  46],
       [-25, 145]])

In [28]:
x.dot(y)

array([[-19,  46],
       [-25, 145]])

In [29]:
np.dot(x,np.ones(3))

array([  6.,  15.])

In [30]:
np.shape(np.ones(3))

(3,)

In [31]:
#numpy.linalg(linear algebra) provdies all the algebric functions related to matrices

In [32]:
x=np.random.randn(5,5)

In [33]:
x

array([[-0.17379141,  0.04606826, -1.71006367, -1.87339011,  0.04286412],
       [-0.81373691,  2.12571092,  1.98997645, -0.57546872, -0.44319946],
       [-0.67906429,  1.4208423 , -1.49778022,  1.04751643,  0.06689337],
       [-1.08912754,  0.73603264,  0.3965585 ,  0.31286531, -0.71223683],
       [ 2.6474356 , -0.0564291 , -0.41332771,  0.77149807, -0.89391279]])

In [41]:
from numpy.linalg import inv,qr

In [39]:
inv(x)

array([[ -6.65998289e-04,   1.41438952e-01,   1.00174735e-02,
         -4.08169312e-01,   2.55806949e-01],
       [  5.21769376e-02,   3.57653160e-01,   3.18471132e-01,
         -2.86415263e-01,   7.72155148e-02],
       [ -2.04775103e-01,   1.72764532e-01,  -2.12321947e-01,
         -7.99263964e-02,  -4.76814502e-02],
       [ -3.50397900e-01,  -1.57906747e-01,   2.07271530e-01,
          7.89393592e-02,   1.41023376e-02],
       [ -2.12995681e-01,   1.80146601e-01,   2.86624945e-01,
         -1.08567912e+00,  -3.31728993e-01]])

In [42]:
np.diag(x)

array([-0.17379141,  2.12571092, -1.49778022,  0.31286531, -0.89391279])

In [43]:
np.trace(x)

-0.1269081928695811

In [45]:
np.linalg.det(x)

-39.997200216400358

In [47]:
np.linalg.eig(x)

(array([-2.59125884+0.j        , -1.15368346+1.37368175j,
        -1.15368346-1.37368175j,  3.33227897+0.j        ,  1.43943860+0.j        ]),
 array([[  4.62812964e-01+0.j        ,  -7.83493017e-02+0.35898446j,
          -7.83493017e-02-0.35898446j,   3.83229865e-01+0.j        ,
          -5.37895137e-01+0.j        ],
        [ -2.38244169e-01+0.j        ,  -5.72011078e-02+0.13379282j,
          -5.72011078e-02-0.13379282j,  -7.19895767e-01+0.j        ,
          -5.60231639e-01+0.j        ],
        [  6.26578348e-01+0.j        ,   1.81367258e-01-0.03268303j,
           1.81367258e-01+0.03268303j,  -3.51508669e-01+0.j        ,
          -2.51553716e-04+0.j        ],
        [  6.14367572e-03+0.j        ,   7.47918327e-02+0.27834389j,
           7.47918327e-02-0.27834389j,  -4.09268507e-01+0.j        ,
           4.39320599e-01+0.j        ],
        [ -5.80004918e-01+0.j        ,   8.52518421e-01+0.j        ,
           8.52518421e-01-0.j        ,   2.09346362e-01+0.j        ,
       

In [49]:
np.linalg.inv(x)

array([[ -6.65998289e-04,   1.41438952e-01,   1.00174735e-02,
         -4.08169312e-01,   2.55806949e-01],
       [  5.21769376e-02,   3.57653160e-01,   3.18471132e-01,
         -2.86415263e-01,   7.72155148e-02],
       [ -2.04775103e-01,   1.72764532e-01,  -2.12321947e-01,
         -7.99263964e-02,  -4.76814502e-02],
       [ -3.50397900e-01,  -1.57906747e-01,   2.07271530e-01,
          7.89393592e-02,   1.41023376e-02],
       [ -2.12995681e-01,   1.80146601e-01,   2.86624945e-01,
         -1.08567912e+00,  -3.31728993e-01]])

In [50]:
#compute the Moore-penrose pseudo-inverse of a square matrix

In [51]:
np.linalg.pinv(x)

array([[ -6.65998289e-04,   1.41438952e-01,   1.00174735e-02,
         -4.08169312e-01,   2.55806949e-01],
       [  5.21769376e-02,   3.57653160e-01,   3.18471132e-01,
         -2.86415263e-01,   7.72155148e-02],
       [ -2.04775103e-01,   1.72764532e-01,  -2.12321947e-01,
         -7.99263964e-02,  -4.76814502e-02],
       [ -3.50397900e-01,  -1.57906747e-01,   2.07271530e-01,
          7.89393592e-02,   1.41023376e-02],
       [ -2.12995681e-01,   1.80146601e-01,   2.86624945e-01,
         -1.08567912e+00,  -3.31728993e-01]])

# Random Number generation

In [52]:
#draw samples from a distribution

In [54]:
np.random.permutation(5)

array([1, 4, 2, 0, 3])

In [60]:
np.random.seed(42)
np.random.rand(5)# to generate the same random sequence

array([ 0.37454012,  0.95071431,  0.73199394,  0.59865848,  0.15601864])

In [61]:
np.random.seed(42)
np.random.rand(5)

array([ 0.37454012,  0.95071431,  0.73199394,  0.59865848,  0.15601864])

In [62]:
np.random.rand(5)

array([ 0.15599452,  0.05808361,  0.86617615,  0.60111501,  0.70807258])

In [70]:
x=np.random.shuffle([1,2,3])
x

In [68]:
np.random.randint(1,6)#draw a random number between a sequence

4

In [72]:
np.random.randn(5,5)#draw samples from a normal distribution with mean 0 and standard deviation 1

array([[-0.2257763 ,  0.0675282 , -1.42474819, -0.54438272,  0.11092259],
       [-1.15099358,  0.37569802, -0.60063869, -0.29169375, -0.60170661],
       [ 1.85227818, -0.01349722, -1.05771093,  0.82254491, -1.22084365],
       [ 0.2088636 , -1.95967012, -1.32818605,  0.19686124,  0.73846658],
       [ 0.17136828, -0.11564828, -0.3011037 , -1.47852199, -0.71984421]])

In [107]:
np.random.binomial(5,0.3,size=5)

array([3, 2, 1, 0, 1])

In [108]:
np.random.normal(5,2,size=6)

array([ 7.35943269,  3.20358412,  6.66959084,  5.59312277,  2.92434025,
        4.84839251])

In [79]:
#similarly beta ,gamma,uniform

# Random walk generator

In [82]:
import random

In [101]:
import random 
position = 0
walk=[position]
steps=1000
for i in range(steps):
    step=1 if random.randint(0,1)==1 else -1
    position += step
    walk.append(position)


In [103]:
walk[:10]

[0, -1, 0, 1, 0, -1, 0, 1, 2, 1]

In [104]:
#now walk is just the cumulative sum of the random steps

In [109]:
nsteps=1000
draws=np.random.randint(0,2,size=nsteps)
steps=np.where(draws>0,1,-1)
walk=steps.cumsum()

In [110]:
walk[:10]

array([ 1,  0, -1, -2, -1, -2, -3, -2, -3, -4], dtype=int32)

In [111]:
walk.min()

-14

In [112]:
np.max(walk)

35

In [113]:
(np.abs(walk)>=10).argmax()#returns the first time it took 10 steps away from the starting point

31

In [114]:
nsteps=1000
nwalks=5000
draws=np.random.randint(0,2,size=(nwalks,nsteps))
steps=np.where(draws>0,1,-1)
walk=steps.cumsum(1)

In [116]:
walk

array([[  1,   2,   3, ..., -38, -37, -38],
       [ -1,   0,  -1, ...,   2,   1,   0],
       [ -1,   0,   1, ...,  66,  65,  64],
       ..., 
       [ -1,   0,  -1, ...,  -4,  -3,  -4],
       [ -1,  -2,  -3, ..., -14, -15, -16],
       [  1,   2,   1, ...,  -2,  -1,  -2]], dtype=int32)